#### Load Data

In [2]:
from pathlib import Path

BASE_DIR = Path().cwd().parent
DATA_PATH = BASE_DIR / "data" / "covid_worldwide.csv"

In [3]:
import pandas as pd

df = pd.read_csv(DATA_PATH)
df.head(3)

,Country/Other,Total Cases,Total Deaths,Total Recovered,Active Cases,Tot Cases/ 1M pop,Deaths/ 1M pop,Total Tests,Tests/ 1M pop,Population
0,Afghanistan,225659,7946,206248.0,11465.0,5537,195,1302555.0,31961.0,40754388
1,Albania,334726,3602,329428.0,1696.0,116777,1257,1941032.0,677173.0,2866374
2,Algeria,271852,6881,183061.0,81910.0,5995,152,230960.0,5093.0,45350148

#### Inspecting Data

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country/Other      221 non-null    str
 1   Total Cases        221 non-null    int64
 2   Total Deaths       221 non-null    int64
 3   Total Recovered    201 non-null    float64
 4   Active Cases       201 non-null    float64
 5   Tot Cases/ 1M pop  221 non-null    int64
 6   Deaths/ 1M pop     221 non-null    int64
 7   Total Tests        211 non-null    float64
 8   Tests/ 1M pop      211 non-null    float64
 9   Population         221 non-null    int64
dtypes: float64(4), int64(5), str(1)
memory usage: 17.4 KB

In [12]:
df.loc[df.isna().any(axis=1)].head(10)

,Country/Other,Total Cases,Total Deaths,Total Recovered,Active Cases,Tot Cases/ 1M pop,Deaths/ 1M pop,Total Tests,Tests/ 1M pop,Population
27,British Virgin Islands,7305,64,NaN,NaN,238757,2092,107339.0,3508269.0,30596
44,Comoros,9109,161,8939.0,9.0,10038,177,NaN,NaN,907419
53,DPRK,4772813,74,4772739.0,0.0,183636,3,NaN,NaN,25990679
67,Faeroe Islands,34658,28,NaN,NaN,703959,569,778000.0,15802409.0,49233
72,French Polynesia,78623,649,NaN,NaN,276682,2284,NaN,NaN,284164
82,Guadeloupe,203235,1021,NaN,NaN,508349,2554,938039.0,2346306.0,399794
88,Honduras,473547,11161,NaN,NaN,46330,1092,1660662.0,162472.0,10221247
91,Iceland,209191,229,NaN,NaN,605661,663,1996384.0,5780036.0,345393
97,Isle of Man,38008,116,NaN,NaN,443335,1353,150753.0,1758422.0,85732
102,Japan,33803572,74694,NaN,NaN,269169,595,100414883.0,799578.0,125584838

In [6]:
print("(Mean deaths, Mean recovered)")
int(df["Total Deaths"].mean()), int(df["Total Recovered"].mean())

(Mean deaths, Mean recovered)

(31290, 3117227)

In [11]:
columns_with_missing_values = df.columns[df.isna().any()].tolist()
print(f"Columns with missing data: {columns_with_missing_values}")

Columns with missing data: ['Total Recovered', 'Active Cases', 'Total Tests', 'Tests/ 1M pop']

In [15]:
missing_values_per_column = []

for column in columns_with_missing_values:
    missing_values_per_column.append(len(df[df[column].isnull()]))

missing_values_per_column

[20, 20, 10, 10]